# Generated by Django 3.1.5 on 2021-01-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210106_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='descriptionp',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default=' ', max_length=3000),
        ),
    ]
