# Generated by Django 3.1.5 on 2021-01-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210106_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
